// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mock/mock_observer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	base "yp-go-short-url-service/internal/observer/base"

	gomock "go.uber.org/mock/gomock"
)

// MockObserver is a mock of Observer interface.
type MockObserver[Event any] struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder[Event]
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder[Event any] struct {
	mock *MockObserver[Event]
}

// NewMockObserver creates a new mock instance.
func NewMockObserver[Event any](ctrl *gomock.Controller) *MockObserver[Event] {
	mock := &MockObserver[Event]{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder[Event]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver[Event]) EXPECT() *MockObserverMockRecorder[Event] {
	return m.recorder
}

// GetID mocks base method.
func (m *MockObserver[Event]) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockObserverMockRecorder[Event]) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockObserver[Event])(nil).GetID))
}

// Notify mocks base method.
func (m *MockObserver[Event]) Notify(ctx context.Context, event Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockObserverMockRecorder[Event]) Notify(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockObserver[Event])(nil).Notify), ctx, event)
}

// MockSubject is a mock of Subject interface.
type MockSubject[Event any] struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectMockRecorder[Event]
	isgomock struct{}
}

// MockSubjectMockRecorder is the mock recorder for MockSubject.
type MockSubjectMockRecorder[Event any] struct {
	mock *MockSubject[Event]
}

// NewMockSubject creates a new mock instance.
func NewMockSubject[Event any](ctrl *gomock.Controller) *MockSubject[Event] {
	mock := &MockSubject[Event]{ctrl: ctrl}
	mock.recorder = &MockSubjectMockRecorder[Event]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubject[Event]) EXPECT() *MockSubjectMockRecorder[Event] {
	return m.recorder
}

// NotifyAll mocks base method.
func (m *MockSubject[Event]) NotifyAll(ctx context.Context, event Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyAll", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyAll indicates an expected call of NotifyAll.
func (mr *MockSubjectMockRecorder[Event]) NotifyAll(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyAll", reflect.TypeOf((*MockSubject[Event])(nil).NotifyAll), ctx, event)
}

// Subscribe mocks base method.
func (m *MockSubject[Event]) Subscribe(observer base.Observer[Event]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", observer)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSubjectMockRecorder[Event]) Subscribe(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSubject[Event])(nil).Subscribe), observer)
}

// Unsubscribe mocks base method.
func (m *MockSubject[Event]) Unsubscribe(observer base.Observer[Event]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", observer)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockSubjectMockRecorder[Event]) Unsubscribe(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockSubject[Event])(nil).Unsubscribe), observer)
}
