// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "description": "Создает короткую ссылку из длинного URL, отправленного в текстовом формате",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "shortener"
                ],
                "summary": "Создать короткую ссылку (текстовый формат)",
                "parameters": [
                    {
                        "description": "Длинный URL для сокращения",
                        "name": "url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Сокращенный URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "URL уже существует в системе",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/shorten": {
            "post": {
                "description": "Создает короткую ссылку из длинного URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shortener"
                ],
                "summary": "Создать короткую ссылку",
                "parameters": [
                    {
                        "description": "Данные для создания короткой ссылки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/json.CreatingShortURLsDTOIn"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Короткая ссылка успешно создана",
                        "schema": {
                            "$ref": "#/definitions/json.CreatingShortURLsDTOOut"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "URL уже существует в системе",
                        "schema": {
                            "$ref": "#/definitions/json.CreatingShortURLsDTOOut"
                        }
                    },
                    "415": {
                        "description": "Неподдерживаемый тип контента",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/shorten/batch": {
            "post": {
                "description": "Создает короткие ссылки из массива длинных URL-ов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shortener"
                ],
                "summary": "Создать короткие ссылки пакетно",
                "parameters": [
                    {
                        "description": "Массив данных для создания коротких ссылок",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/batch.URLRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Короткие ссылки успешно созданы",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/batch.URLResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "415": {
                        "description": "Неподдерживаемый тип контента",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Проверяет доступность базы данных и возвращает статус сервиса",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Проверка здоровья сервиса",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "health check failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{shortURL}": {
            "get": {
                "description": "Перенаправляет пользователя на оригинальный длинный URL по короткой ссылке",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "redirect"
                ],
                "summary": "Перенаправление на длинный URL",
                "parameters": [
                    {
                        "type": "string",
                        "example": "abc123",
                        "description": "Короткий URL",
                        "name": "shortURL",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Перенаправление на длинный URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "batch.URLRequest": {
            "type": "object",
            "required": [
                "correlation_id",
                "original_url"
            ],
            "properties": {
                "correlation_id": {
                    "description": "CorrelationID - уникальный идентификатор для корреляции запроса/ответа\nrequired: true\nexample: \"1\"",
                    "type": "string"
                },
                "original_url": {
                    "description": "OriginalURL - длинный URL для сокращения\nrequired: true\nexample: \"https://www.example.com/very/long/url/that/needs/to/be/shortened\"",
                    "type": "string"
                }
            }
        },
        "batch.URLResponse": {
            "type": "object",
            "properties": {
                "correlation_id": {
                    "description": "CorrelationID - уникальный идентификатор для корреляции запроса/ответа\nexample: \"1\"",
                    "type": "string"
                },
                "short_url": {
                    "description": "ShortURL - сокращенный URL\nexample: \"http://localhost:8080/abc123\"",
                    "type": "string"
                }
            }
        },
        "json.CreatingShortURLsDTOIn": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "description": "URL - длинный URL для сокращения\nrequired: true\nexample: \"https://www.example.com/very/long/url/that/needs/to/be/shortened\"",
                    "type": "string"
                }
            }
        },
        "json.CreatingShortURLsDTOOut": {
            "type": "object",
            "properties": {
                "result": {
                    "description": "Result - сокращенный URL\nexample: \"http://localhost:8080/abc123\"",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "URL Shortener Service API",
	Description:      "Сервис для сокращения длинных URL-адресов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
